<div class="menu">
                <div class="header col-10">
                <a href="./biblioteca.php" class="title" ><h1 class="col-10" >SISTEMA BIBLIOTECÁRIO DO COLTEC</h1></a>
                <div class="headerOp">
                    <a href="./forms.php" class="button btn btn-warning fw-bold">Cadastrar livro</a>
                    <div id="divBusca">
                        <form action="result.php" method="post">
                            <input type="text" name="txtBusca" class="fw-bold" id="txtBusca" required placeholder="Buscar..." />
                            <button style={{color: #2c363f}} class="btn btn-warning fw-bold" type="submit" id="btnBusca"><i
                                    class=" search fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
                </div>
                
                

            </div>