<?php
function exibeRodape(){
    echo '<footer class="py-3 my-4 bg-dark text-white" style="margin-bottom: 0!important;">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item">
                        <a href="https://github.com/PedroHenAssuncao" class="nav-link px-2 text-muted">GitHub Pedro</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/ivonpr" class="nav-link px-2 text-muted">GitHub Ivo</a>
                    </li>
                </ul>
                <p class="text-center text-muted">Developed with ❤️ by Pedro Henrique Assunção & Ivo Nascimento Pereira Rodrigues</p>
            </footer>' ;
    
}
?>